name: First Workflow
on: workflow_dispatch
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: print greeting
        run: echo "Hello World"
      - name: end
        run: echo "Done!"
  second-job:
    runs-on: ubuntu-latest
    steps:
      - name: print greeting
        run: echo "Helooo"
